name: CI Pipeline

on: [push]

jobs:
  check_working_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training
        run: python train.py

      - name: Run testing
        run: python test.py